package ddb

import (
	"database/sql"
	"log"
	"time"

	"github.com/pborman/uuid"
)

func insertMember(name string) {
	tm := time.Now()
	// db, err := sql.Open("mysql", "root:4116bbDD#@(47.244.236.195:3306)/stbweb?charset=utf8&parseTime=True&loc=Local")
	db, err := sql.Open("mysql", "root:123456@(127.0.0.1:3306)/stbweb?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		log.Println(err)
		return
	}
	defer db.Close()
	for t := 0; t < 1000; t++ {
		tx, err := db.Begin()
		if err != nil {
			log.Println(err)
			return
		}
		stmt, err := tx.Prepare(`INSERT INTO task(
					task_id, 
					user,
					task_type,
					spec,
					Is_save,
					create_time,
					complete,
					errors_mes,
					execution_time) VALUES
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?),
					(?,?,?,?,?,?,?,?,?)`)
		if err != nil {
			log.Println(err)
			tx.Rollback()
			return
		}
		if _, err = stmt.Exec(
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
			uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now()); err != nil {
			// logrus.WithFields(logrus.Fields{"sql-exec": err}).Error("job")
			log.Println(err)
			tx.Rollback()
			return
		}

		tx.Commit()
	}

	log.Println("总用时：", time.Since(tm))
}

//事务提交+sql数量+每天sql包含数据量
func insertMembers(name string) {
	tm := time.Now()
	// db, err := sql.Open("mysql", "root:4116bbDD#@(47.244.236.195:3306)/stbweb?charset=utf8&parseTime=True&loc=Local")
	db, err := sql.Open("mysql", "root:123456@(127.0.0.1:3306)/stbweb?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		log.Println(err)
		return
	}
	defer db.Close()
	for t := 0; t < 50; t++ { //事务提交次数
		tx, err := db.Begin()
		if err != nil {
			log.Println(err)
			return
		}
		for i := 0; i < 20; i++ { //每次事务中的sql语句
			//每条sql中的数据插入量
			stmt, err := tx.Prepare(`INSERT INTO task(
						task_id, 
						user,
						task_type,
						spec,
						Is_save,
						create_time,
						complete,
						errors_mes,
						execution_time) VALUES
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?),
						(?,?,?,?,?,?,?,?,?)`)
			if err != nil {
				log.Println(err)
				return
			}
			if _, err = stmt.Exec(
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now(),
				uuid.NewUUID().String(), "qwer", "qwer", "qwer", "qwer", time.Now(), "qwer", "qwer", time.Now()); err != nil {
				log.Println(err)
				return
			}
			if i%100 == 0 {
				log.Println(name, i, "-用时：", time.Since(tm))
			}
		}
		tx.Commit()
	}
	log.Println("总用时：", time.Since(tm))
}
